name: book_nook_app
description: Book recommendation application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  carousel_slider: ^4.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  get_it: ^7.2.0
  http: ^0.13.4
  internet_connection_checker: ^0.0.1+4
  shared_preferences: ^2.0.15
  loading_animation_widget: ^1.2.0+3
  im_animations: ^0.1.2
  flutter_snake_navigationbar: ^0.6.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lang/ar.json
    - lang/en.json
    - assets/images/logo.png
    - assets/images/bookmark-icon.png
    - assets/images/user.png
    - assets/images/4x/book.png

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 800
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 200

    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Bold.ttf
          weight: 800
        - asset: assets/fonts/Barlow-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Barlow-Medium.ttf
          weight: 500
        - asset: assets/fonts/Barlow-Regular.ttf
          weight: 400
        - asset: assets/fonts/Barlow-Light.ttf
          weight: 200
